name: postman-test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    strategy:
      matrix:
        node-version: [14.x]
      # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres

        # Provide the password for postgres
        env:
          POSTGRES_USER: ${{env.DB_USERNAME}}
          POSTGRES_PASSWORD: ${{env.DB_PASSWORD}}
          POSTGRES_DB: ${{env.DB_NAME}}
        # needed because the postgres container does not provide a healthcheck
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Check out Git repositor
        uses: actions/checkout@v1
        with:
          ref: master
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm install
      - name: Install newman
        run: npm install -g newman
      - name: Install nodemon
        run: npm install -g nodemon
      - name: Run the API and Postman's tests
        env:
          POSTGRES_HOST: ${{env.DB_HOST}}
          POSTGRES_PORT : ${{ job.services.postgres.ports[5432] }}
          DBURL: postgresql://${{env.DB_USERNAME}}:${{env.DB_PASSWORD}}@${{env.DB_HOST}}:${{env.DB_PORT}}/${{env.DB_NAME}}
          APP_PORT: ${{env.APP_PORT}}
          FIREBASE_API_KEY: ${{env.FIREBASE_API_KEY}}
          FIREBASE_AUTH_DOMAIN: ${{env.FIREBASE_AUTH_DOMAIN}}
          FIREBASE_PROJECT_ID: ${{env.FIREBASE_PROJECT_ID}}
          FIREBASE_STORAGE_BUCKET: ${{env.FIREBASE_STORAGE_BUCKET}}
          FIREBASE_MESSAGING_ID: ${{env.FIREBASE_MESSAGING_ID}}
          FIREBASE_APP_ID: ${{env.FIREBASE_APP_ID}}
          FIREBASE_MEASUREMENT_ID: ${{env.FIREBASE_MEASUREMENT_ID}}
        run: |
          npm start &
          sleep 60
          newman run "Cars_Location.postman_collection.json"
        #postgresql://[user[:password]@][netloc][:port][/dbname][?param1=value1&...]
